---
# tasks file for artemis-7.6
#- name: Install Artemis server to the path "{{ ARTEMIS_HOME }}"
#  copy: 
#   src: files/apache-artemis-2.16.0 
#   dest: "{{ ARTEMIS_HOME }}"

- name: Creating broker instance {{ARTEMIS_INSTANCE}} under {{ARTEMIS_HOME}}
  shell: "sh {{ARTEMIS_HOME}}/bin/artemis create {{ARTEMIS_HOME}}/bin/{{ARTEMIS_INSTANCE}} --user {{AMQ_USER}} --password {{AMQ_PASSWORD}} --allow-anonymous {{ALLOW_ANONYMOUS}}"

